# Generated by rust2rpm 26
%bcond_without check

%global crate linutil_tui

Name:           rust-linutil_tui
Version:        24.9.28
Release:        %autorelease
Summary:        Chris Titus Tech's Linux Toolbox - Linutil is a distro-agnostic toolbox designed to simplify everyday Linux tasks

License:        MIT
URL:            https://crates.io/crates/linutil_tui
Source:         %{crates_source}
Source2:        https://raw.githubusercontent.com/ChrisTitusTech/linutil/refs/heads/main/LICENSE
# Manually created patch for downstream crate metadata changes
Patch:          linutil_tui-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Chris Titus Tech's Linux Toolbox - Linutil is a distro-agnostic toolbox
designed to simplify everyday Linux tasks.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%doc cool_tips.txt
%{_bindir}/linutil

%prep
%autosetup -n %{crate}-%{version} -p1
cp -p %SOURCE2 .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
