# Generated by rust2rpm 26
%bcond_without check

%global crate linutil

Name:           linutil
Version:        2024.09.28
Release:        %autorelease
Summary:        Linutil is a toolbox designed to simplify everyday Linux tasks

SourceLicense:  MIT
License:  ((MIT OR Apache-2.0) AND Unicode-DFS-2016) AND (Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT) AND (Apache-2.0 OR BSD-2-Clause OR MIT) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (ISC) AND (MIT)
URL:            https://github.com/ChrisTitusTech/linutil
Source:         https://github.com/ChrisTitusTech/linutil/archive/refs/tags/%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires: desktop-file-utils

%global _description %{expand:
Chris Titus Tech's Linux Toolbox - Linutil is a distro-agnostic toolbox
designed to simplify everyday Linux tasks.}

%description %{_description}


%files
%license LICENSE.dependencies LICENSE
%doc README.md
%doc cool_tips.txt
%{_bindir}/linutil
%{buildroot}%{_datadir}/applications/*.desktop

%prep
%autosetup -n %{name}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
desktop-file-install --dir=%{buildroot}%{_datadir}/applications ./linutil.desktop

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
