# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate ansi-to-tui

Name:           rust-ansi-to-tui
Version:        6.0.0
Release:        %autorelease
Summary:        Library to convert ansi color coded text into ratatui::text::Text type from ratatui library

License:        MIT
URL:            https://crates.io/crates/ansi-to-tui
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library to convert ansi color coded text into ratatui::text::Text type
from ratatui library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd-devel %{_description}

This package contains library source intended for building other packages which
use the "simd" feature of the "%{crate}" crate.

%files       -n %{name}+simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zero-copy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zero-copy-devel %{_description}

This package contains library source intended for building other packages which
use the "zero-copy" feature of the "%{crate}" crate.

%files       -n %{name}+zero-copy-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
