# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           rust-serial-unix
Version:        0.4.0
Release:        %autorelease
Summary:        Serial port implementation for Unix

SourceLicense:  MIT
# FIXME: paste output of %%cargo_license_summary here
License:        (MIT) AND (Apache-2.0 OR MIT)
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/solomoncyj/serial-unix
Source:         https://github.com/solomoncyj/serial-unix/archive/refs/tags/0.4.0.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Serial port implementation for Unix.}

%description %{_description}

%prep
%autosetup -n %{name}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md

%changelog
%autochangelog
