# Generated by rust2rpm 26
%bcond_without check

Name:           linutil
Version:        2024.09.28
Release:        %autorelease
Summary:        inutil is a toolbox designed to simplify everyday Linux tasks

SourceLicense:  MIT
License:  ((MIT OR Apache-2.0) AND Unicode-DFS-2016) AND (Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT) AND (Apache-2.0 OR BSD-2-Clause OR MIT) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (ISC) AND (MIT)

# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/ChrisTitusTech/linutil/
Source:         https://github.com/ChrisTitusTech/%{name}/archive/refs/tags/%{version}.tar.gz
Patch0:         metadata.patch
BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  desktop-file-utils

%global _description %{expand:
Chris Titus Tech's Linux Toolbox - Linutil is a distro-agnostic toolbox
designed to simplify everyday Linux tasks.}

%description %{_description}

%prep
%autosetup -n linutil-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
install -Dpm 0755 target/rpm/linutil -t %{buildroot}%{_bindir}/
desktop-file-install --dir=%{buildroot}%{_datadir}/applications  --set-key=Exec  --set-value=%{_bindir}/linutil  ./linutil.desktop

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%doc cargo-lock-merge.txt
%{_bindir}/linutil
%{_datadir}/applications/*.desktop

%changelog
%autochangelog
