# Generated by rust2rpm 26
%bcond_with check

%global forgeurl https://github.com/ChrisTitusTech/linutil/
%global tag  2025.02.13

%forgemeta

Name:           linutil
Version:        %{tag}
Release:        %autorelease
Summary:        inutil is a toolbox designed to simplify everyday Linux tasks

SourceLicense:  MIT
License:  ((MIT OR Apache-2.0) AND Unicode-DFS-2016) AND (Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT) AND (Apache-2.0 OR BSD-2-Clause OR MIT) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (ISC) AND (MIT)

# LICENSE.dependencies contains a full license breakdown

URL:            %{forgeurl}
Source0:         %{forgesource}
Source1: https://github.com/Chris-Titus-Docs/linutil-docs/blob/main/static/images/favicon.png
BuildRequires:  desktop-file-utils
BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Chris Titus Tech's Linux Toolbox - Linutil is a distro-agnostic toolbox
designed to simplify everyday Linux tasks.}

%description %{_description}

%prep
%forgesetup
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
install -Dpm 0755 target/rpm/linutil -t %{buildroot}%{_bindir}/
mkdir %{buildroot}%{_datadir}/icons/ -p
mkdir %{buildroot}%{_mandir}/linutil -p
cp %{SOURCE2} %{buildroot}%{_datadir}/icons/linutil.png
mv ./man/* /%{buildroot}%{_mandir}/linutil
desktop-file-install --dir=%{buildroot}%{_datadir}/applications  \
                                    --set-key=Exec  --set-value=%{_bindir}/linutil   \
                                    --set-key=Icon  --set-value=%{_datadir}/icons/linutil.png    \
                                    ./linutil.desktop

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_mandir}/linutil/
%doc  docs/*
%doc  ./tui/cool_tips.txt
%{_datadir}/icons/linutil.png
%{_bindir}/linutil
%{_datadir}/applications/*.desktop

%{_bindir}/linutil
%{_datadir}/applications/*.desktop

%changelog
%autochangelog
