# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate app-rummage

Name:           rust-app-rummage
Version:        0.2.8
Release:        %autorelease
Summary:        Find installed and running applications on Linux

License:        MIT
URL:            https://crates.io/crates/app-rummage
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * Allow nix 0.29 until we have 0.30 packaged
Patch:          app-rummage-fix-metadata.diff
# * patch tests to not fail
Patch1:         https://gitlab.com/mission-center-devs/app-detection/-/commit/029ae0329235ad0f19c4c26e1acd54712cf63a31.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Find installed and running applications on Linux.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
