[package]
license-files = [
  "LICENSE",
]

[[package.extra-sources]]
number = 1
file = "https://github.com/roboplc/virtual-terminal/raw/refs/heads/main/LICENSE"
comments = [
  "include license file",
  "https://github.com/roboplc/virtual-terminal/issues/1",
]

[scripts]
prep.post = ["""\
# copy in license file
cp -p %{SOURCE1} ."""]

