# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate vt100-ctt

Name:           rust-vt100-ctt
Version:        0.16.0
Release:        %autorelease
Summary:        Library for parsing terminal data - up-to-date version

License:        MIT
URL:            https://crates.io/crates/vt100-ctt
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for parsing terminal data - up-to-date version.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tui-term-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tui-term-devel %{_description}

This package contains library source intended for building other packages which
use the "tui-term" feature of the "%{crate}" crate.

%files       -n %{name}+tui-term-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
