[package]
license-files = [
  "LICENSE.*",
]

[[package.extra-patches]]
number = 1
file = "https://patch-diff.githubusercontent.com/raw/faern/triggered/pull/5.diff"
comments = [
  "include license file",
]


