# Generated by rust2rpm 26
%bcond_with check
%global debug_package %{nil}

%global crate serial2

Name:           rust-serial2
Version:        0.2.28
Release:        %autorelease
Summary:        Cross platform serial ports

License:        BSD-2-Clause OR Apache-2.0
URL:            https://crates.io/crates/serial2
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          serial2-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cross platform serial ports.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-BSD
%doc %{crate_instdir}/CHANGELOG
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+doc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+doc-devel %{_description}

This package contains library source intended for building other packages which
use the "doc" feature of the "%{crate}" crate.

%files       -n %{name}+doc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+doc-cfg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+doc-cfg-devel %{_description}

This package contains library source intended for building other packages which
use the "doc-cfg" feature of the "%{crate}" crate.

%files       -n %{name}+doc-cfg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rs4xx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rs4xx-devel %{_description}

This package contains library source intended for building other packages which
use the "rs4xx" feature of the "%{crate}" crate.

%files       -n %{name}+rs4xx-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unix-devel %{_description}

This package contains library source intended for building other packages which
use the "unix" feature of the "%{crate}" crate.

%files       -n %{name}+unix-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+windows-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+windows-devel %{_description}

This package contains library source intended for building other packages which
use the "windows" feature of the "%{crate}" crate.

%files       -n %{name}+windows-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
