# Generated by rust2rpm 27
%bcond check 0
%global debug_package %{nil}

%global crate gbm

Name:           rust-gbm
Version:        0.18.0
Release:        %autorelease
Summary:        Libgbm bindings for rust

License:        MIT
URL:            https://crates.io/crates/gbm
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Libgbm bindings for rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+drm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+drm-devel %{_description}

This package contains library source intended for building other packages which
use the "drm" feature of the "%{crate}" crate.

%files       -n %{name}+drm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+drm-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+drm-support-devel %{_description}

This package contains library source intended for building other packages which
use the "drm-support" feature of the "%{crate}" crate.

%files       -n %{name}+drm-support-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+import-egl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+import-egl-devel %{_description}

This package contains library source intended for building other packages which
use the "import-egl" feature of the "%{crate}" crate.

%files       -n %{name}+import-egl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+import-wayland-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+import-wayland-devel %{_description}

This package contains library source intended for building other packages which
use the "import-wayland" feature of the "%{crate}" crate.

%files       -n %{name}+import-wayland-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "use_bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+use_bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-backend" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-server-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-server-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-server" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-server-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
