[package]
license-files = [
  "LICENSE",
]

[[package.extra-sources]]
number = 1
file = "https://github.com/brendanzab/gl-rs/raw/refs/heads/master/LICENSE"
comments = [
  "include license file",
]

[scripts]
prep.post = ["""\
# copy in license file
cp -p %{SOURCE1} ."""]
