# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate gbm-sys

Name:           rust-gbm-sys
Version:        0.4.0
Release:        %autorelease
Summary:        Bindgen generated unsafe libgbm wrapper

License:        MIT
URL:            https://crates.io/crates/gbm-sys
Source:         %{crates_source}
# * include license file
Source1:        https://github.com/Smithay/gbm.rs/raw/refs/heads/master/LICENSE
# Manually created patch for downstream crate metadata changes
# * patch feature flags and add pkg config dep
Patch:          gbm-sys-fix-metadata.diff
# * make bindgen unconditinal
# * use system gbm
# * https://github.com/Smithay/gbm.rs/pull/52
Patch1:         52-ds.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  mesa-libgbm-devel

%global _description %{expand:
Bindgen generated unsafe libgbm wrapper.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+update_bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+update_bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "update_bindings" feature of the "%{crate}" crate.

%files       -n %{name}+update_bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "use_bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+use_bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# copy in license file
cp -p %{SOURCE1} .


%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
