# Generated by rust2rpm 27
%bcond check 1

%global crate cargo-rpmstatus

Name:           rust-cargo-rpmstatus
Version:        0.2.2
Release:        %autorelease
Summary:        Cargo-tree for RPM packaging

License:        (MIT OR Apache-2.0) AND GPL-3.0-or-later
URL:            https://crates.io/crates/cargo-rpmstatus
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * bump bzip version bounds
Patch:          cargo-rpmstatus-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cargo-tree for RPM packaging.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:         ((MIT OR Apache-2.0) AND GPL-3.0-or-later) AND ((MIT OR Apache-2.0) AND Unicode-DFS-2016) AND (0BSD OR Apache-2.0 OR MIT) AND (Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT) AND (Apache-2.0 OR BSD-2-Clause OR MIT) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR ISC OR MIT) AND (Apache-2.0 OR MIT) AND (Apache-2.0 OR MIT OR Zlib) AND (BSD-3-Clause) AND (Custom License File) AND (ISC) AND (MIT) AND (MIT OR Unlicense) AND (MPL-2.0)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-Apache-2.0
%license LICENSE-GPL-3.0-or-later
%license LICENSE-MIT
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/cargo-rpmstatus
%{_mandir}/man1/cargo-rpmstatus.1*

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
# set up man pages
mkdir -p %{buildroot}/%{_mandir}/man1
cp ./cargo-rpmstatus.1 %{buildroot}/%{_mandir}/man1

%if %{with check}
%check
# * crate will attempt to connect to internet to run tests
%cargo_test -- -- --skip db::tests::online_check_version_reqs
%endif

%changelog
%autochangelog
