[scripts]
install.post = [
"# set up man pages",
"mkdir -p %{buildroot}/%{_mandir}/man1",
"cp ./cargo-rpmstatus.1 %{buildroot}/%{_mandir}/man1",]


[tests]
skip = [
"db::tests::online_check_version_reqs"]
comments = [
"crate will attempt to connect to internet to run tests"]

[package]
cargo-toml-patch-comments = [
"bump bzip version bounds"]
extra-files = [
"%{_mandir}/man1/cargo-rpmstatus.1*"]
