# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate tree-sitter-language

Name:           rust-tree-sitter-language
Version:        0.1.2
Release:        %autorelease
Summary:        Tree-sitter Language type, used by the library and by language implementations

License:        MIT
URL:            https://crates.io/crates/tree-sitter-language
Source:         %{crates_source}
Source2:        https://raw.githubusercontent.com/tree-sitter/tree-sitter/refs/heads/master/LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The tree-sitter Language type, used by the library and by language
implementations.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml
%license  LICENSE
%prep
%autosetup -n %{crate}-%{version} -p1
cp -p %SOURCE2 .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
