# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate bmart-derive

Name:           rust-bmart-derive
Version:        0.1.4
Release:        %autorelease
Summary:        Bohemia Automation common tools library (derive macros)

License:        MIT
URL:            https://crates.io/crates/bmart-derive
Source:         %{crates_source}
# * include license file
# * https://github.com/eva-ics/bmart/pull/1
Source1:        https://github.com/eva-ics/bmart/raw/2d8447ea8731fb933bb1d94d6df0c099ff28f5bd/LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Bohemia Automation common tools library (derive macros).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# copy in license file
cp -p %{SOURCE1} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
