# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate gl

Name:           rust-gl
Version:        0.14.0
Release:        %autorelease
Summary:        OpenGL bindings

License:        Apache-2.0
URL:            https://crates.io/crates/gl
Source:         %{crates_source}
# * include license file
Source1:        https://github.com/brendanzab/gl-rs/raw/refs/heads/master/LICENSE
# Manually created patch for downstream crate metadata changes
Patch:          gl-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
OpenGL bindings.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# copy in license file
cp -p %{SOURCE1} .
#glutin version used id out-of-date
rm -rf examples/

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
